"""empty message

Revision ID: 7b22bce4cec3
Revises: 38cecf0d13bf
Create Date: 2021-01-27 12:01:35.221251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b22bce4cec3'
down_revision = '38cecf0d13bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('date_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'date_created')
    # ### end Alembic commands ###
